project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!*.test.qmd"

website:
  title: "CS 104 (Applied Computing) at Calvin University"
  navbar:
    right:
      - href: index.qmd
  sidebar:
    contents:
      - "index.qmd"
      - "lab-instructions.qmd"
      - "tips-resources.qmd"
      - auto: "classes/"
        icon: "person-workspace"
  page-navigation: true

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-depth: 4
    toc-expand: 4 
    toc_float: true
