project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!slides/02*/*"
    - "!slides/03*/*"
    - "!slides/04*/*"
    - "!slides/05*/*"
    - "!slides/06*/*"
    - "!slides/07*/*"
    - "!*.test.qmd"
    - "!handouts/02*/*"
    - "!handouts/03*/*"
    - "!handouts/04*/*"
    - "!handouts/05*/*"
    - "!handouts/06*/*"
    - "!handouts/07*/*"

website:
  title: "CS 104 (Applied Computing) at Calvin University"
  navbar:
    right:
      - href: index.qmd
  sidebar:
    contents:
      - "index.qmd"
      - "lab-instructions.qmd"
      - "tips-resources.qmd"
      - auto: "slides/"
        icon: "person-workspace"
  page-navigation: true

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-depth: 4
    toc-expand: 4 
    toc_float: true
