project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!*.test.qmd"

website:
  title: "CS 104 (Applied Computing) at Calvin University"
  navbar:
    right:
      - href: index.qmd
  sidebar:
    contents:
      - "index.qmd"
  page-navigation: true

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc_depth: 2
    toc_float: true
