---
title: "04 - Loops"
format:
  html:
    toc-expand: 4
---

Objectives for this unit:

## Loops - basics
-   Write while loops to repeat code based on a condition.
-   Prevent infinite loops by ensuring loop control variables are correctly modified.
-   Write for loops to iterate over sequences.
-   Use the range() function to generate sequences for iteration.
-   Write and use nested while and for loops.
-   Understand how repetition statements reveal judgements about what can be scaled.

## Loops - Python techniques
-   Use loop control statements (break, continue, pass) to manage the flow of loops.
-   Iterate through sequences using for loops and while loops.
-   Iterate through dictionary keys, values, and key-value pairs, using dictionary methods (e.g., items(), keys(), values())
-   Write basic list comprehensions to create new lists.
-   Use list comprehensions to transform and filter elements from existing lists.
-   Reflect on the ethics of automating procedures through algorithms.