---
title: "02 - Data Types"
format:
  html:
    toc-expand: 4
---

Objectives for this unit:

## Sequence types
-   Differentiate between lists, tuples, and strings.
-   Understand how data types encode values about what is being represented.
-   Create lists and tuples with different types of elements.
-   Index and access elements in sequences.
-   Explain the difference between mutable and immutable objects when assigning values.
-   Use common list methods (e.g., append(), remove(), extend(), sort()).
-   Use slicing to access subsets of list and tuple elements.

## Dictionary type
-   Explain the concept and use cases of dictionaries in Python.
-   Create dictionaries with key-value pairs.
-   Access, add, modify, and delete elements in dictionaries.
-   Reflect on the limits of representations and data structures in algorithms

## Numpy arrays
-   Explain the purpose of the Numpy library in the context of scientific computing.
-   Create Numpy arrays from lists and tuples.
-   Use functions like numpy.array(), numpy.zeros(), numpy.ones(), numpy.arange() to create arrays.
-   Access and modify elements in Numpy arrays using indexing and slicing
-   Perform element-wise operations on Numpy arrays (e.g., addition, subtraction, multiplication, division).
-   Reshape Numpy arrays using the reshape() method.
-   Use Numpy functions to perform operations (e.g., numpy.sum(), numpy.mean(), numpy.max()).