---
title: "06 - Classes"
format:
  html:
    toc-expand: 4
---

Objectives for this unit:

## Classes - basics
-   Explain the principles of object-oriented programming (OOP) and its benefits.
-   Define a class using the class keyword.
-   Understand the purpose of the `__init__` method for initializing objects.
-   Create objects (instances) from a class.
-   Access and modify object attributes and methods.
-   Reflect on the digitization of the world with digital objects

## Classes - Python techniques
-   Define and use class methods and instance methods.
-   Use special methods (e.g., `__str__`, `__repr__`, `__add__`, `__len__`) to define behavior for built-in operations.
-   Understand and explain what is open-source software and what are its characteristics and variations

## Classes - inheritance and polymorphisc
-   Explain the concept of inheritance and its advantages.
-   Create subclasses that inherit from a parent class.
-   Override methods in a subclass.
