# Programming and virtues

-   The last decades have seen a resurgence on the discussion of virtues in academic scholarship: G. E. M. Anscombe, Philippa Foot, John McDowell, Rosalind Hursthouse and Alasdair MacIntyre
-   Thinking about virtues help us to go beyond the limitations of an ethics of duty (deontological) and an ethics of utility (utilitarianism)
    -   The focus is not in the actions of someone, but in the individual himself, seen as situated inside a narrative and a social practice
-   According to Alasdair MacIntyre, every social practice has standards of excellence (or constitutive rules) that guarantee their "internal goods". These are the virtues.
    -   Individuals show virtues inside these practices as they insert them inside a big narrative unity of life.
-   Programming is a kind of social practice. What are its virtues?

## What are virtues?

-   From the Latin virtus, associated with the Greek arête, which means “excellence”. Aristotle used this term to talk about "moral virtues", i.e., the excellences of character.
-   It is possible to identify different virtue traditions:

+-------------------------------+----------------------------------------+-------------------------------+---------------------+-----------------------------+
|                               | Judaism                                | Aristotelianism               | Confucianism        | Buddhism                    |
+===============================+========================================+===============================+=====================+=============================+
| The idea of the supreme good  | Shalom                                 | Eudaimonia                    | Dao                 | Nirvana                     |
+-------------------------------+----------------------------------------+-------------------------------+---------------------+-----------------------------+
| The exemplary virtuous person | Makarios (blessed), Tsadic (righteous) | Phronimoi                     | Junzi               | Sangha                      |
+-------------------------------+----------------------------------------+-------------------------------+---------------------+-----------------------------+
| The way to moral growth       | Torah (ex.: Psalm 119)                 | Phronesis                     | Li (moral rites)    | The Noble Eightfold Path    |
+-------------------------------+----------------------------------------+-------------------------------+---------------------+-----------------------------+
| Who is moral human being      | Tselem Elohim (image of God)           | Political and rational animal | Xing (many strands) | Anatman, pratitya-samutpada |
+-------------------------------+----------------------------------------+-------------------------------+---------------------+-----------------------------+

-   There are similarities, but also some fundamental differences. They also identify different fundamental virtues:

+------------------------------+-------------------------------------------------------------+----------------------+---------------------------------+
| Aristotelianism              | Christianity                                                | Confucianism         | Buddhism                        |
+==============================+=============================================================+======================+=================================+
| Courage\                     | The Beatitudes (Matthew 5:1-12) The four cardinal virtues:\ | Loyalty (Zhong)\     | The "perfections" (Pāramitās):\ |
| Temperance\                  | - Justice\                                                  | Filial piety (Xiao)\ | Dāna (generosity)\              |
| Liberality\                  | - Prudence\                                                 | Benevolence (Ren)\   | Sīla (appropriate conduct)\     |
| Magnificence\                | - Courage\                                                  | Affection (Ai)\      | Nekkhamma (renouncement)\       |
| Magnanimity\                 | - Temperance\                                               | Honesty (Xin)\       | Paññā (wisdom)\                 |
| Ambition\                    | The three theological virtues: - Faith\                     | Righteousness (Yi)\  | Viriya (energy)\                |
| Patience Friendship Honesty\ | - Hope\                                                     | Harmony (He)\        | Khanti (patience)\              |
| Good mood\                   | - Love                                                      | Peace (Ping)\        | Sacca (honesty)\                |
| Modesty\                     |                                                             | Respect (Li)\        | Adhiṭṭhāna (determination)\     |
| Justice                      |                                                             | Wisdom (Zhi)\        | Mettā (good will)\              |
|                              |                                                             | Integrity (Lian)\    | Upekkhā (tranquility)           |
|                              |                                                             | Shame (Chi)          |                                 |
+------------------------------+-------------------------------------------------------------+----------------------+---------------------------------+

> “The Tao, which others may call Natural Law or Traditional Morality or the First Principles of Practical Reason or the First Platitudes, is not one among a series of possible systems of value. It is the sole source of all value judgments. If it is rejected, all value is rejected. If any value is retained, it is retained. The effort to refute it and raise a new system of value in its place is self-contradictory. There has never been, and never will be, a radically new judgment of value in the history of the world. What purport to be new systems or…ideologies…all consist of fragments from the Tao itself, arbitrarily wrenched from their context in the whole and then swollen to madness in their isolation, yet still owing to the Tao and to it alone such validity as they posses.” ― C.S. Lewis, The Abolition of Man

## Intellectual virtues

-   Lots of development today in the area of virtues that need to be present in our search for truth. See, for example, this [book](https://www.amazon.com/Intellectual-Virtues-Regulative-Epistemology-Cognitive/dp/0199575703).

+---------------------------------+------------------------------------+
| Virtues                         | Vices                              |
+=================================+====================================+
| Curiosity\                      | Curiosity\                         |
| Perceptiveness\                 | Indifference\                      |
| Discernment\                    | Naivety\                           |
| Honesty\                        | Dishonesty\                        |
| Integrity\                      | Corruption\                        |
| Autonomy\                       | Dogmatism\                         |
| Humility\                       | Self-deception\                    |
| Parsimony\                      | Diffusivity\                       |
| Perseverance\                   | Obstination\                       |
| Justification\                  | Wishful thinking\                  |
| Depth\                          | Superficiality\                    |
| Empathy/Benevolence\            | Obtuseness/Stupidity\              |
| Creativity                      | Closemindedness                    |
+---------------------------------+------------------------------------+

## The technomoral virtues (Shannon Vallor)

-   Philosopher [Shannon Vallor has discussed](https://academic.oup.com/book/25951) the need of virtues that are adequate for our current technological society.

| Virtue          | Related Virtues                               | Technological Issue                                                     |
|-----------------|-----------------------------------------------|-------------------------------------------------------------------------|
| 1. Honesty      | Trust, integrity                              | New forms of communication                                              |
| 2. Self-control | Temperance, discipline, moderation            | New temptations (media, entertainment)                                  |
| 3. Humility     | Modesty, reverence, wonder                    | Optimism or pessimism regarding progress                                |
| 4. Justice      | Responsibility, equity, reciprocity           | Who receives benefits and harms from technological advancement          |
| 5. Courage      | Hope, perseverance, fortitude                | Risks are greater, on a global level                                    |
| 6. Empathy      | Compassion, benevolence, sympathy             | Media that encourages indifference and virulence                        |
| 7. Care         | Generosity, love, self-sacrifice, charity     | Delegation of tasks to machines can eliminate human contact             |
| 8. Civility     | Respect, commitment, friendship               | Individualism and fragmentation into bubbles                            |
| 9. Flexibility  | Patience, indulgence, tolerance, mercy        | Pluralism and globalization                                            |
| 10. Perspective | Discernment, attention, understanding         | Division of labor makes it difficult to visualize short- and long-term impacts |
| 11. Magnanimity | Equanimity, courage, ambition                | Lack of leadership to deal with impacts                                 |
| 12. Wisdom       | Unifies all others                             |                                                                         |

## How does one grow in virtues?

-   Vallor also calls attention to some common steps predicated by the virtue traditions that indicate moral growth:

1.  **Moral habituation**: repetition, memorization, observation of exemplary people, ascetic discipline
2.  **Relational understanding**: discern my role, my position and my duties in the context I find myself (child, parent, citizen, etc.)
3.  **Reflective self-examination**: "Search me, O God, and know my heart! Try me and know my thoughts! And see if there be any grievous way in me, and lead me in the way everlasting!" (Psalm 139.23-24)
4.  **Intentional self-direction of moral development**: a resolution to improve, and seeking for help. "With my whole heart I seek you; let me not wander from your commandments!" (Psalm 119.10)
5.  **Moral attention and discernment**: sensitivity to discern “morally salient” characteristics of a circumstance.
6.  **Prudential judgment** (*phronesis*): ability to deliberate and adapt principles and rules to the situation (which may be new and unforeseen). Example: Jesus healed in the Sabbath.
7.  **Appropriate extent of moral concern**: "who is my neighbor?" Remember the parable of the good samaritan. To know how to be concerned with the right people, in the right time, in the right degree, in the right way".

## Analysing programming practice

-   What are the virtues we tried to practice this semester?
    -   Try to go to our content and discern them. Use a list of virtues of a tradition and try to see them there.
-   What are some possible vices in the programming practice? How can we act to counteract them?
-   How to develop myself as a virtuous programmer?